### ISSUE TITLE
The project won't compile with Strip Debug Symbols During Copy set to yes

### ISSUE THREAD

**Issue by rflmalheiros** [ManifestWebDesign/twitter-connect-plugin#1]
PBXCp Error: strip /Users/user/WebstormProjects/autoline.application2/platforms/ios/Autoline/Resources/TwitterKitResources.bundle/SystemConfiguration.framework/SystemConfiguration: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip exited with 1

**Comment by TheBosZ** [comment]
Unfortunately, the docs for Twitter integration don't talk about what needs to happen to do a release build.

I've figured out that if you set "strip debug symbols during copy" to "No", the build works just fine but when you go to upload to the store, it complains about incorrect signing.

**Comment by rflmalheiros** [comment]
I had replaced TwitterKitResources.bundle with only the twitter sdk, created by the fabric in another app. That solved my problem. I let "strip debug symbols during copy" to "Yes". No error occurred. o//

**Comment by TheBosZ** [comment]
Are you able to upload to the app store? The store complained about signatures when we tried to upload.

**Comment by rflmalheiros** [comment]
Yes, upload. No error about signature.

**Comment by TheBosZ** [comment]
Can you walk me through the exact steps you did to make it work?

**Comment by rflmalheiros** [comment]
1 - Create a empty iOS xCode project, 
2 - Run the Fabric app to configure the project.
3 - Install Only the twitter SDK.
4 - Copy the TwitterKitResources.bundle (located at <EmptyProject>/TwitterKit.framework/Resources)
5 - Replace the TwitterKitResources.bundle in the target project you where you installed the twitter-connect-plugin (located at <TargetProjectFolder>/platforms/ios/<AppName>/Resources)

**Comment by rflmalheiros** [comment]
I can send you the TwitterKitResources.bundle to you and you only replace in the target project.

**Comment by TheBosZ** [comment]
Sure! You could send me a pull request if you'd like. Or I'll try it your way to see if I can do it myself in like 30 minutes.

**Comment by rflmalheiros** [comment]
Ok, i'm forking

**Comment by TheBosZ** [comment]
Awesome! #2 fixes it! Thanks a lot!
