### ISSUE TITLE
Can't sign-up on Fabric for cordova project

### ISSUE THREAD

**Issue by Mr-Drake** [ManifestWebDesign/twitter-connect-plugin#10]
Stuck on Fabric plugin step. I use WebStorm, a plug-in does not create any buttons. Ie no further registration to continue?

**Comment by TheBosZ** [comment]
It looks like the process has changed recently. I'm not sure what needs to happen.

**Comment by jinuem** [comment]
Let me tell you how i created Fabric Key and Consumer API and Secret..  Little Trick needs to be done to get this Keys. (i am not sure, its right way, but it works )

1. Go to https://fabric.io/ create account and Organization.
2. Wait for the approval.
3. Download Plugin for your Android Studio/Xcode Mac
4. Install the Plugin (Steps will be given in Fabric Website)
5. Create dummy cordova project in the same bundle id of your existing cordova project (example: com.xxx.projectname) (boz you dont have to messup with cordova codebase)
6. Open that dummy android/ios project in your android studio or xcode. 
7. Click Fabric Plugin and Login with the Fabric account which you registered in 1st step.
8. Follow the steps shown in the Fabric Plugin (Mostly Click Next, Next, Next)
9. Finally Fabric Plugin ask you to put build. DO THE BUILD. 
10. Once the Build is succeeded, Fabric will create APP (Name of the App and Bundle ID will be used from your dummy project which you used) in your Fabric account.
11. Now go to https://fabric.io/settings/organizations ( You will find Fabric API Key ) Which you need to download this Plugin.
12. Go to the apps section https://fabric.io/settings/apps . You will see your app which fabric created from ur first build.  
13. Click the Dashboard https://fabric.io/dashboard . You will here get the Consumer Key and Consumer Secret..


Whew... Thats it :)

**Comment by TheBosZ** [comment]
@Mr-Drake please try these steps and let us know if it works!

**Comment by Dineshrajaa** [comment]
Till 10 I have followed in Android Studio but when I go to https://fabric.io/settings/organizations 
still I am getting redirected to https://fabric.io/onboard 
Plese help me to get the Fabric Account ID

**Comment by TheBosZ** [comment]
@Dineshrajaa You'll need to follow all of the steps laid out by @jinuem. You can't get to the organizations page until you've done the "onboarding" process. It's stupid, I know.

**Comment by Dineshrajaa** [comment]
@TheBosZ yes I have followed all the steps 
I just created a sample app and imported that cordova app in Android studio and applied those codes which Fabric plugin told me to apply and then build the app Build then checked in the fabric.io but still I couldn't get the Fabric Key :(

**Comment by TheBosZ** [comment]
If the Fabric website is still directing you to onboarding you still haven't gone through the onboarding process with them.

**Comment by Dineshrajaa** [comment]
Now I have got a mail regarding the approval so the above steps worked thanks @jinuem and @TheBosZ

**Comment by jinuem** [comment]
@Dineshrajaa  Welcome :)
