### ISSUE TITLE
Problem in iOS

### ISSUE THREAD

**Issue by jinuem** [ManifestWebDesign/twitter-connect-plugin#11]
Getting errors like
Fabric.h Not found
Twitterkit.h not found.

Are you sure frameworks are included in this plugin?

**Comment by TheBosZ** [comment]
Is this the same issue as #9? Unfortunately, I have no idea what's causing the problem. My recommendation is to try a fork of this plugin to see if it works for you.

**Comment by jinuem** [comment]
@TheBosZ ... Yeah Same Issue... I tried to replaced the fabric, twitterkit Frameworks and also included CoreText, Twitter Core, TwitterKitResource Framework.. But still i get some more "Apple mach-o linker error"..

Ok let me try to fix more. but mean while please look into this. This is the only plugin which exist properly for Twitter Connect for Cordova...

**Comment by jinuem** [comment]
@TheBosZ  I have found the solution, Checked with my iphone and android.. Works fine.. Will update the required frameworks in my fork. N let you know. Check and Push in your repo. :)

**Comment by jinuem** [comment]
@TheBosZ 
Fixed the issues on iOS!

Here is my folk repo : https://github.com/jinuem/twitter-connect-plugin
I have removed old Fabric and TwitterKit framework and added new. And also added few dependency frameworks to work on iOS. 
Review the Code and Push to NPM Repo!
(P.S: TwitterKit Wont work Below iOS7. So change the Development to iOS 7 or Higher.. )

Thanks.

**Comment by TheBosZ** [comment]
Great! Can you please submit a pull request to me so I can merge the changes?

**Comment by jinuem** [comment]
Sure will do that :)

**Comment by TheBosZ** [comment]
Great, thanks!
