### ISSUE TITLE
IOS :Build Failed

### ISSUE THREAD

**Issue by Moussawi7** [ManifestWebDesign/twitter-connect-plugin#14]
Hi,
I created a demo project that include only this plugin and the result of the build is
```
The following build commands failed:
	CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/TwitterConnect.o HelloCordova/Plugins/twitter-connect-plugin/TwitterConnect.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```
Platform:IOS.
Cordova :5.3.3
Xcode: version 7
Thank you.

**Comment by TheBosZ** [comment]
I honestly have no idea why that is happening.

If anyone can help out here, it would be appreciated!

**Comment by Moussawi7** [comment]
Hi @TheBosZ ,
First thanks for your response.
The problem solved by changing the deployment target from ***6.0*** to ***7.0***.
Thank you.

**Comment by TheBosZ** [comment]
Great!
