### ISSUE TITLE
Android login results in "Failed login session", iOS working

### ISSUE THREAD

**Issue by JohnnySheffield** [ManifestWebDesign/twitter-connect-plugin#16]
I got the plugin working on iOS without any major problems, but on Android it fails with:  "Failed login session"

I believe this is the line where the error bubbles up:
https://github.com/ManifestWebDesign/twitter-connect-plugin/blob/master/src/android/TwitterConnect.java#L79

I'm using:

`$ cordova -v
`
`5.3.3
`
`$ ionic -v
`
`1.7.7
`
`$ cordova plugin list
`
`cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-media-capture 1.0.1 "Capture"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.1.1-dev "Whitelist"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
twitter-connect-plugin 0.5.0 "Twitter Connect"
`

As you can see, i'm using ionic for building and running this project - but on iOS it's working as expected.

Can you please provide some info where did i fail or what to do next?
Do i need to do something additional in the Android studio except installing the Fabric twitter plugin?

**Comment by TheBosZ** [comment]
It's quite possible that the Android SDK changes recently.
Can you log the exception and see what it says?

You actually shouldn't need to do anything with Android studio. You can do the entire compile process from the command line.

**Comment by JohnnySheffield** [comment]
If i log the error directly from the plugin, i only get "Failed login session". Here's the trace when running 'ionic run android', if it matters, i'm have Android studio v1.3.1 installed. (I've tried to pull a clean version of my project and do the build all over again to see if it will fix, but no luck, having the same issue). Can i compile the project with some flags to get more understandable trace?

$ ionic run android
Running command: /Users/MaliBuda/befitted3/hooks/after_prepare/010_add_platform_class.js /Users/MaliBuda/befitted3
add to body class: platform-android
Running command: /Users/MaliBuda/befitted3/hooks/after_prepare/020_remove_sass_from_platforms.js /Users/MaliBuda/befitted3
Running command: /Users/MaliBuda/befitted3/platforms/android/cordova/run 
ANDROID_HOME=/Users/MaliBuda/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
WARNING : No target specified, deploying to device '20bf308b'.
Running: /Users/MaliBuda/befitted3/platforms/android/gradlew cdvBuildDebug -b /Users/MaliBuda/befitted3/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true
Download https://maven.fabric.io/public/com/twitter/sdk/android/twitter/1.4.0/twitter-1.4.0.pom
Download https://maven.fabric.io/public/com/twitter/sdk/android/tweet-ui/1.1.0/tweet-ui-1.1.0.pom
Download https://maven.fabric.io/public/com/twitter/sdk/android/twitter-core/1.3.2/twitter-core-1.3.2.pom
Download https://maven.fabric.io/public/io/fabric/sdk/android/fabric/1.3.0/fabric-1.3.0.pom
Download https://maven.fabric.io/public/com/twitter/sdk/android/tweet-composer/0.7.3/tweet-composer-0.7.3.pom
Download https://maven.fabric.io/public/com/digits/sdk/android/digits/1.4.0/digits-1.4.0.pom
Download https://maven.fabric.io/public/com/twitter/cobalt/performance-metrics/0.2.0/performance-metrics-0.2.0.pom
Download https://repo1.maven.org/maven2/com/squareup/picasso/picasso/2.3.2/picasso-2.3.2.pom
Download https://repo1.maven.org/maven2/com/squareup/picasso/picasso-parent/2.3.2/picasso-parent-2.3.2.pom
Download https://repo1.maven.org/maven2/com/squareup/retrofit/retrofit/1.6.1/retrofit-1.6.1.pom
Download https://repo1.maven.org/maven2/com/squareup/retrofit/parent/1.6.1/parent-1.6.1.pom
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://maven.fabric.io/public/com/twitter/cobalt/performance-metrics/0.2.0/performance-metrics-0.2.0.aar
Download https://repo1.maven.org/maven2/com/squareup/picasso/picasso/2.3.2/picasso-2.3.2.jar
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://repo1.maven.org/maven2/com/squareup/retrofit/retrofit/1.6.1/retrofit-1.6.1.jar
Download https://maven.fabric.io/public/io/fabric/sdk/android/fabric/1.3.0/fabric-1.3.0.aar
Download https://maven.fabric.io/public/com/twitter/sdk/android/twitter-core/1.3.2/twitter-core-1.3.2.aar
Download https://maven.fabric.io/public/com/twitter/sdk/android/tweet-ui/1.1.0/tweet-ui-1.1.0.aar
Download https://maven.fabric.io/public/com/twitter/sdk/android/tweet-composer/0.7.3/tweet-composer-0.7.3.aar
Download https://maven.fabric.io/public/com/digits/sdk/android/digits/1.4.0/digits-1.4.0.aar
Download https://maven.fabric.io/public/com/twitter/sdk/android/twitter/1.4.0/twitter-1.4.0.aar
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42100Library
:prepareComDigitsSdkAndroidDigits140Library
:prepareComTwitterCobaltPerformanceMetrics020Library
:prepareComTwitterSdkAndroidTweetComposer073Library
:prepareComTwitterSdkAndroidTweetUi110Library
:prepareComTwitterSdkAndroidTwitter140Library
:prepareComTwitterSdkAndroidTwitterCore132Library
:prepareIoFabricSdkAndroidFabric130Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:preDexDebug
:dexDebug
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 52.388 secs
Built the following apk(s):
    /Users/MaliBuda/befitted3/platforms/android/build/outputs/apk/android-debug.apk
Using apk: /Users/MaliBuda/befitted3/platforms/android/build/outputs/apk/android-debug.apk
Installing app on device...
Launching application...
LAUNCH SUCCESS

**Comment by TheBosZ** [comment]
You can modify the code that gets put on the device.

I won't be able to look into the issue until at least Monday.

If you'd like to try it, change the line where it logs the error:
https://github.com/ManifestWebDesign/twitter-connect-plugin/blob/master/src/android/TwitterConnect.java#L79

To log the exception instead. You can also run Android studio in "Debug"
mode and set a breakpoint there.

**Comment by TheBosZ** [comment]
When I try it, everything works fine.

Can you try removing and then readding the plugin?

**Comment by JohnnySheffield** [comment]
I tried to clean everything, pull my app again, install the plugins and voila - it worked just like a breeze! Seems this was a case of an PEBKAC error. Thank you for the help!  :dancers:

**Comment by TheBosZ** [comment]
:+1:

**Comment by alouane** [comment]
I had the same problem, the reason was that I used a wrong secret key, I missed the last 3 chars :)

**Comment by darkokostic** [comment]
I get Failed login session when I try to login with Twitter in my app without official Twitter App installed on my device. I am working in Ionic 2, what can I do?

**Comment by TheBosZ** [comment]
It should work just fine without the official Twitter app (it will instead show an in-app browser window with the login page).

Please follow the other troubleshooting steps in this thread and open a new issue if you're still having problems.

**Comment by lastamazing7** [comment]
hello , in my case when i install Twitter app in my device it will working fine without app i got same error "Failed login session". 
but how can it work without Twitter app ?? plz guide me..

**Comment by dwlrathod** [comment]
Hello in my case this was working since yesterday today i got the error.
Removing plugin and install again worked for me for now!

**Comment by setu1421** [comment]
I am getting the same **Failed login session** error in android.. Any solution for this?

**Comment by kushaldias** [comment]
i am getting the failed login session error as well. i tried everything mentioned above. please help

**Comment by kamakshi417** [comment]
Me too facing same issue. Anyone have idea about this.

**Comment by maxgomes92** [comment]
Same issue

**Comment by kamakshi417** [comment]
Fallow this link.  https://www.javascripttuts.com/adding-twitter-authentication-with-firebase-in-ionic/
and don't consider firebase. If it is helps you let me know.

**Comment by Fatimaboet** [comment]
Same issue with Ionic 3. Anyone have idea about this.

**Comment by jayeshkorat18** [comment]
I am getting "Request failed: forbidden (403)" in twitter login in iOS.

**Comment by ferdil** [comment]
See the response on #66
