### ISSUE TITLE
Using the token.

### ISSUE THREAD

**Issue by pykler** [ManifestWebDesign/twitter-connect-plugin#18]
Can the app keys be accessed in the controller securely? We need the app keys to communicate with twitter post login, any ideas what is the best and most secure way to pull them?

**Comment by TheBosZ** [comment]
I would recommend another plugin, [like this one](https://github.com/apla/me.apla.cordova.app-preferences), to get the keys out of the preferences. 

The keys you're looking for are "TwitterConsumerKey" and "TwitterConsumerSecret".
