### ISSUE TITLE
Get email

### ISSUE THREAD

**Issue by shakogegia** [ManifestWebDesign/twitter-connect-plugin#19]
How can i get user email?

**Comment by TheBosZ** [comment]
Unfortunately, that's beyond the scope of this plugin. This plugin is strictly for logging in and out using Twitter.

We'd like to expand it to cover more of the functionality in the Twitter SDK in the future.

**Comment by Tarekajaj** [comment]
@TheBosZ any update about getting the email ?

**Comment by TheBosZ** [comment]
@Tarekajaj No, retrieving the user's email is outside the scope of this plugin.

If you want to get your app whitelisted by Twitter, you can request the user's email from the REST API: https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by abhishekthakur1995** [comment]
@TheBosZ if I enable email permission from the dashboard at dev.twitter.com then can I get email using this plugin.

**Comment by TheBosZ** [comment]
@abhishekthakur1995 No, retrieving the user's email is outside the scope of this plugin. You can get their email from this REST endpoint:
https://dev.twitter.com/rest/reference/get/account/verify_credentials
