### ISSUE TITLE
Phonegap Build support?

### ISSUE THREAD

**Issue by smithmeisterUK** [ManifestWebDesign/twitter-connect-plugin#22]
Original plugins site (https://build.phonegap.com/plugins/6187) lists the following for Phonegap Build:

<plugin name="twitter-connect-plugin" spec="0.5.0"> source="pgb">
    <param name="FABRIC_KEY" value="..." />
</gap:plugin>

Ignoring the obvious typos, the namespace should be a full address and as such is failing during build... any update/clarification on this?

**Comment by TheBosZ** [comment]
I didn't know this plugin was listed in the Build repository. 

According to the [build docs](http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins), the correct format would be:
````<plugin name="twitter-connect-plugin" spec="0.5.0" source="npm" />````

Try using this format and it should work.

If it doesn't, please reopen this issue and we can try something else.

**Comment by smithmeisterUK** [comment]
Hi Nathan

I agree, that should work (along with its parameter for FABRIC_KEY) but
gives a build error. Should the name be in reverse domain format?

Thanks
Brian

**Comment by TheBosZ** [comment]
I honestly don't know. I've never used Phonegap Build and have no experience with it.

Please let me know if you can figure it out.

**Comment by smithmeisterUK** [comment]
Hi Nathan

Just to let you know I've got it working with...

<gap:plugin name="twitter-connect-plugin" source="npm" spec="0.5.0">
    <param name="FABRIC_KEY" value=" ... " />
</gap:plugin>

... plus needed to specify iOS7 for TwitterKit ...

<preference name="deployment-target" value="7.0" />
<preference name="TwitterConsumerKey" value=" ... " />
<preference name="TwitterConsumerSecret" value=" ... " />

Thanks
Brian

**Comment by TheBosZ** [comment]
Fantastic! I'll add the info to the Readme.
