### ISSUE TITLE
Fabric key confusion

### ISSUE THREAD

**Issue by prateek-sparx** [ManifestWebDesign/twitter-connect-plugin#3]
Hello,

firstly great work for that plugin, And I need your little help in configuring the Fabric app,
the url you have discussed "https://fabric.io/settings/organizations/" is not there on the fabric site, please give some brief description/Steps about to create the Key.

Thanks.

**Comment by TheBosZ** [comment]
Have you created an account with Fabric? The organizations page is only available if you have an account.

You can also the [read the help about organizations](https://dev.twitter.com/fabric/overview/teams).

**Comment by prateek-sparx** [comment]
Thanks for your quick review!!.
Is that Api returns the profile picture of the user

**Comment by TheBosZ** [comment]
No, the login API doesn't return the user picture. If you'd like to contribute a PR to get it, I'd be happy to merge it in. I'm going to close this issue, please open a new one if you need to.
