### ISSUE TITLE
Authentication not working on android 4.4

### ISSUE THREAD

**Issue by mparisot** [ManifestWebDesign/twitter-connect-plugin#31]
Hello,

I'm trying to figure out what is going on because I cannot login using Twitter only on android 4.4 (it works on android 6 and I can't test on 5 right now but it was working a few days ago)

After investigating a lot what's happening is that the TwitterConnect.onActivityResult method is never called after the user authenticate.

It is called once when all is initialized by cordova to "reset the activity callbacks" but never when I am done authenticating.

I put some breakpoints to figure out what was going on and it passes through OAuthActivity.onComplete in Twitter SDK so that should trigger the onActivityResult from what I understand.

The Android 6 phones uses SSO authent but I somehow forced them to use OAuth and it worked fine.

It also works fine on iOs.

Thank you for any help on that matter

**Comment by mparisot** [comment]
Something I just realized is that the TwitterConnect.onActivityResult triggered by the reset of callbacks on android 4.4 is not called on android 6 which might be a clue

And I tested on versions .5.0 and 0.6.0 of the plugin

**Comment by TheBosZ** [comment]
Hmm... That's really odd. 

This plugin was developed specifically for an app targeting 4.4 (the latest at the time).

If I get some free time, I'll try to see if I can reproduce the problem.

Thanks for your efforts to report as much information as possible!

**Comment by mparisot** [comment]
Ok I spent a bit more time and trying with a clean app I could pinpoint the problem to the AndroidLaunchMode

I was in singleInstance mode and switching to anything else fixes the problem so I switched to singleTask

<preference name="AndroidLaunchMode" value="singleTask"/>

It also fixed the same problem with Facebook plugin that I saw later.
