### ISSUE TITLE
Including parameter "include_email" inside showuser() methode

### ISSUE THREAD

**Issue by alouane** [ManifestWebDesign/twitter-connect-plugin#43]
Hi,
It it possible to add some parameters to the ShowUser() methode or even change the requested api from "/users/show" to "/account/verify_credentials" so that I can get user's email adress?

Cheers

**Comment by ferdil** [comment]
Ideally you could add a new method to call the verify_credentials API - Use a similar mechanism to the one used for /users/show

**Comment by fkamlesh** [comment]
Hi,
I'm also try to get email using this [plugin](https://github.com/ManifestWebDesign/twitter-connect-plugin#showuser)

My app is approved to access email from twitter. Then how can get the email.

How to implement this [documentation](https://dev.twitter.com/rest/reference/get/account/verify_credentials)

"include_email" into 

TwitterConnect.showUser(
  function(result) {
    console.log('User Profile:');
    console.log(result);
    console.log('Twitter handle :'+result.userName);
  }, function(error) {
    console.log('Error retrieving user profile');
    console.log(error);
  }
);

Please any one help. Thanks in advance.

**Comment by alouane** [comment]
Hi,
You can update your java class => com\manifestwebdesign\twitterconnect:


```
interface UserService {
		@GET("/1.1/users/show.json")
		void show(@Query("user_id") long id, Callback<Response> cb);
		@GET("/1.1/account/verify_credentials.json")
		void show_with_email(@Query("user_id") long id, @Query("include_email") boolean include_email, Callback<Response> cb);
	}
```

	private void showUser(final CallbackContext callbackContext) {
		cordova.getThreadPool().execute(new Runnable() {
			@Override
			public void run() {
				UserServiceApi twitterApiClient = new UserServiceApi(Twitter.getSessionManager().getActiveSession());
				UserService userService = twitterApiClient.getCustomService();
				userService.show(Twitter.getSessionManager().getActiveSession().getUserId(), new Callback<Response>() {
					@Override
					public void success(Result<Response> result) {
						try {
							callbackContext.success(new JSONObject(new String(((TypedByteArray) result.response.getBody()).getBytes())));
						} catch (JSONException e) {
							e.printStackTrace();
						}
					}
					@Override
					public void failure(TwitterException exception) {
						Log.v(LOG_TAG, "Twitter API Failed "+exception.getLocalizedMessage());
						callbackContext.error(exception.getLocalizedMessage());
					}
				});
			}
		});
	}
	private void showUserEmail(final CallbackContext callbackContext) {
		cordova.getThreadPool().execute(new Runnable() {
			@Override
			public void run() {
				UserServiceApi twitterApiClient = new UserServiceApi(Twitter.getSessionManager().getActiveSession());
				UserService userService = twitterApiClient.getCustomService();
				userService.show_with_email(Twitter.getSessionManager().getActiveSession().getUserId(), true, new Callback<Response>() {
					@Override
					public void success(Result<Response> result) {
						try {
							callbackContext.success(new JSONObject(new String(((TypedByteArray) result.response.getBody()).getBytes())));
						} catch (JSONException e) {
							e.printStackTrace();
						}
					}

					@Override
					public void failure(TwitterException exception) {
						Log.v(LOG_TAG, "Twitter API Failed " + exception.getLocalizedMessage());
						callbackContext.error(exception.getLocalizedMessage());
					}
				});
			}
		});
	}`

Hope it helps.

Cheers

**Comment by dotnetdreamer** [comment]
@alouane any hint on iOS ?
