### ISSUE TITLE
Android cordova 3.6 does not work with this plugin

### ISSUE THREAD

**Issue by govindshah** [ManifestWebDesign/twitter-connect-plugin#5]
Hi,

I am trying to install "twitter-connect-plugin" with cordova 3.6 for Android and it does not install since it uses gradle can you tell me a way to make it work with cordova 3.6?

Thanks
Govind

**Comment by TheBosZ** [comment]
Unfortunately the gradle requirement is from the Twitter library itself.

If there's a way to do it, I don't have any idea how.

It's possible that you could grab the libraries directly.

Is there some reason why you can't upgrade?

**Comment by TheBosZ** [comment]
Sorry, because of the Gradle requirement, I'm marking this as won't fix.
