### ISSUE TITLE
Multiple dex files define Lcom/google/gson/JsonSerializer

### ISSUE THREAD

**Issue by kavi707** [ManifestWebDesign/twitter-connect-plugin#53]
Hi,

When I try to build Android. I got following error.

What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/gson/JsonSerializer;

I'm building a ionic app using twitter-connect-plugin & geo-fence cordova plugins. In twitter fabric SDK use com.google.code.gson:gson:2.2.4, but from geo-fence use its newer version com.google.code.gson:gson:2.3.0. Becuase of this version conflicts I get above error when I try build the Android application.

 Please help. Thanks in advance.

**Comment by mohamedsharaf** [comment]
i confirm this issue same with me

**Comment by kavi707** [comment]
Hi,

As I mentioned in the question this happens because of gson:gson:2.3.0 & gson:gson:2.2.4 are conflicting in mentioned plugins.
This can resolve by excluding older version (gson:gson:2.3.0) from the project.
To do that you have to add following code phrase to build.gradle file in android platform.

File: platforms/android/build.gradle
Add following to dependencies
   compile("com.google.code.gson:gson:2.3") {
       exclude module: 'gson:2.2.4'
   }

or

If you are ok to edit the plugin and user
File: plugins/twitter-connect-plugin2/src/android/twitter.gradle
Add following to dependencies
   compile("com.google.code.gson:gson:2.3") {
       exclude module: 'gson:2.2.4'
   }
