### ISSUE TITLE
Plugin not returning email from twitter even though the email permissions are enabled?

### ISSUE THREAD

**Issue by abhishekthakur1995** [ManifestWebDesign/twitter-connect-plugin#56]
I have whitelisted my app i.e I have enabled the email giving permission on https://apps.twitter.com and the auth page of the plugin is also showing that the app has access to user email Id but still no email field is there in the returned callback response.
<img src="https://user-images.githubusercontent.com/24711924/27087382-857ac020-5072-11e7-8d07-abbf465bbcc2.png" width="250">

**Comment by akhikokayaba944** [comment]
please tell me how to get email
