### ISSUE TITLE
What is Fabric API Key ?

### ISSUE THREAD

**Issue by mayurbaldha** [ManifestWebDesign/twitter-connect-plugin#6]
At twitter Developer Apps we have only

Twitter Consumer Key & 
Twitter Consumer Secret..

What is Fabric API Key ?

**Comment by TheBosZ** [comment]
To be able to use the Twitter SDK, named Fabric, you have to sign up and get a Fabric API key. Follow the instructions under the ["Get a Fabric API key"](https://github.com/ManifestWebDesign/twitter-connect-plugin#get-a-fabric-api-key) section.

**Comment by mayurbaldha** [comment]
as we create app at

dev.twitter.com/apps

we get

Consumer Key (API Key)84roj88shJ2dpducuSvvFtAVM
Consumer Secret (API Secret)
s4vJWeGqftZyeF4ILa4XuOoZBaLEW0Fxhl3D9fzob9qLv85rcv

where is FABRIC KEY ?


On Thu, Jul 16, 2015 at 1:48 AM, Nathan Kerr <notifications@github.com>
wrote:

> To be able to use the Twitter SDK, named Fabric, you have to sign up and
> get a Fabric API key. Follow the instructions under the "Get a Fabric API
> key"
> <https://github.com/ManifestWebDesign/twitter-connect-plugin#get-a-fabric-api-key>
> section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManifestWebDesign/twitter-connect-plugin/issues/6#issuecomment-121734091>
> .
>



-- 
*Thanks & Regards,*

*Mayur G. Baldha+91 9033470045 /+91 99794 07617*

**Comment by TheBosZ** [comment]
Please do not post your keys in a public place. You'll have to regenerate them.

Please follow the steps outlined in  ["Get a Fabric API key"](https://github.com/ManifestWebDesign/twitter-connect-plugin#get-a-fabric-api-key)
