### ISSUE TITLE
Email Include

### ISSUE THREAD

**Issue by usama-ayub** [ManifestWebDesign/twitter-connect-plugin#63]
hi all,

 login response is:
userName: 'myuser',
   userId: '12358102',
    secret: 'tokenSecret'
    token: 'accessTokenHere'

but i need also email how i can get email

**Comment by usama-ayub** [comment]
@TheBosZ

**Comment by TheBosZ** [comment]
Again, I no longer maintain nor use this plugin.

Your issue is already discussed here: https://github.com/ManifestWebDesign/twitter-connect-plugin/issues/19 

Sorry, I can't even close this issue as a duplicate.

**Comment by usama-ayub** [comment]
ok i understand thanks for your response
