### ISSUE TITLE
Fabric stuck at onboard page

### ISSUE THREAD

**Issue by eng-mnabil** [ManifestWebDesign/twitter-connect-plugin#7]
I've created an account, but i am now stuck at this page: 
https://fabric.io/onboard
It asks me to choose 1 IDE out of 5 that i am not using, and i can't pass that page!
Even when i try open organizations page https://fabric.io/settings/organizations/ , i get redirected to onboard page

Please advice,
Thanks

**Comment by TheBosZ** [comment]
Just select something to get through the onboarding process. Twitter's idea of "helping" isn't very helpful.

**Comment by eng-mnabil** [comment]
Thanks, i choosed eclipse, and after building and running the application, i finally got the api key.

**Comment by ubeutenm** [comment]
I am stuck at https://fabric.io/onboard/pending
Stupid idea to "help me"

**Comment by carlosaiello** [comment]
The key is the same for both iOS and Android, and it can be found (without following the wizzard) on:
https://fabric.io/kits/android/crashlytics/install
https://fabric.io/kits/ios/crashlytics/install
