### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;

### ISSUE THREAD

**Issue by MingxuanLi** [ManifestWebDesign/twitter-connect-plugin#8]
Hi,

I am getting the following exceptions when I install the twitter plugin together with Facebook and Push Plugin:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

Any idea on how to resolve this ? Thanks

**Comment by TheBosZ** [comment]
Open up the  platforms/android/libs/ folder and look for a file named  android-support-vXX.jar. For me, it was v14.jar. Delete it and try again.

**Comment by trinhvanhuy** [comment]
I got same issue as well
p/s : i'm not found android-support-vXX.jar in platforms/android/libs/

**Comment by TheBosZ** [comment]
What files are listed in that folder?

**Comment by jinuem** [comment]
Are you using Facebook Connect Plugin in the same project?
I am also facing this Multiple Dex error. Once i remove Facebook Connect. Twitter Works fine!

**Comment by trinhvanhuy** [comment]
yes, but is there any way we can use facebook connect plugin and twitter connect plugin together ? i have to provide both way in the application ?

**Comment by jinuem** [comment]
Seems Both Plugins use same Dependencies. Have to look how to fix this error. :) Will let you know.

**Comment by jinuem** [comment]
@TheBosZ  May i know what **android-support-Vx.jar** you included in this plugin?

**Comment by jinuem** [comment]
**@trinhvanhuy @MingxuanLi Hey i found out the Solution for this.. **
Twitter Connect Plugin Includes com.android.support V4 which is already included in other plugins like Facebook Connect. So Just mention your build.gradle to exclude com.android.support v4 module. and Try build.

Go to your Platforms/android/ Open build.gradle

Add following code to the end.

**configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}**

**Comment by trinhvanhuy** [comment]
Thanks jinuem :+1:

**Comment by TheBosZ** [comment]
Thanks for helping troubleshoot!

**Comment by tpanhorst** [comment]
You may want to put this in the steps for setup if you can't fix it altogether.  I installed this plugin fresh and had this issue and couldn't resolve it until I found this issue.

**Comment by TheBosZ** [comment]
@tpanhorst Done! Thanks!
