### ISSUE TITLE
Problem between twitter-connect and Fabric

### ISSUE THREAD

**Issue by alejandrocragnolini-santex** [ManifestWebDesign/twitter-connect-plugin#9]
Hi guys,

I'm trying to use twitter-connect adding it like this:
`cordova plugin add twitter-connect-plugin --variable FABRIC_KEY=''`

Then I'm trying to compile the app getting this error:
`TwitterConnect.m:4:9: fatal error: 'Fabric/Fabric.h' file not found
#import <Fabric/Fabric.h>
        ^
1 error generated.`

By the way I'm on a Mac trying to build an ionic app for ios.

Do you know any probable causes for this?

Thanks in advance!

**Comment by avilaton** [comment]
+1 same thing happening to me right now on MAC, any ideas?

**Comment by TheBosZ** [comment]
Crud. Unfortunately, I have very little insight on the iOS side of the plugin. If I get some time this week, I'll see if I can figure it out.

Any further information or research would be very helpful.

**Comment by alejandrocragnolini-santex** [comment]
This is the error log:
`CompileC build/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/i386/TwitterConnect.o Project/Plugins/twitter-connect-plugin/TwitterConnect.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/currentUser/Projects/Project/client/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/Users/currentUser/Downloads/adt-bundle-mac-x86_64-20140321/sdk/platform-tools:/Users/currentUser/Downloads/adt-bundle-mac-x86_64-20140321/sdk/tools:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/local/mysql/bin:/usr/local/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Project-generated-files.hmap -I/Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Project-own-target-headers.hmap -I/Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Project-all-target-headers.hmap -iquote /Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Project-project-headers.hmap -I/Users/currentUser/Projects/Project/client/platforms/ios/build/emulator/include -I/Users/currentUser/Projects/Project/client/platforms/ios/build/emulator/usr/local/lib/include -I/Users/currentUser/Projects/Project/client/platforms/ios/build/UninstalledProducts/include -I/Users/currentUser/Projects/Project/client/platforms/ios/build/emulator -I/Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/DerivedSources/i386 -I/Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/DerivedSources -F/Users/currentUser/Projects/Project/client/platforms/ios/build/emulator -FProject/Plugins/twitter-connect-plugin -include /Users/currentUser/Projects/Project/client/platforms/ios/build/sharedpch/Project-Prefix-dzwboldzypvvclcnnbyhwyfhgdoo/Project-Prefix.pch -MMD -MT dependencies -MF /Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/i386/TwitterConnect.d --serialize-diagnostics /Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/i386/TwitterConnect.dia -c /Users/currentUser/Projects/Project/client/platforms/ios/Project/Plugins/twitter-connect-plugin/TwitterConnect.m -o /Users/currentUser/Projects/Project/client/platforms/ios/build/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/i386/TwitterConnect.o
/Users/currentUser/Projects/Project/client/platforms/ios/Project/Plugins/twitter-connect-plugin/TwitterConnect.m:4:9: fatal error: 'Fabric/Fabric.h' file not found
#import <Fabric/Fabric.h>
        ^
1 error generated.

** BUILD FAILED **
`

**Comment by TheBosZ** [comment]
Possibly one of the forks has fixed the error. [This one](https://github.com/zo0r/twitter-connect-plugin) looks to have done a lot of work on the iOS side.

**Comment by alejandrocragnolini-santex** [comment]
Thanks a lot @TheBosZ! I'll give it a try and comment here what happened.

**Comment by alejandrocragnolini-santex** [comment]
@TheBosZ it worked like a charm!

I'm sorry I can't provide more information or any possible causes. I hope this helps someone else.

Thanks a lot!

**Comment by avilaton** [comment]
@TheBosZ Perhaps the changes from the fork could be integrated here to avoid problems for other users. @zo0r could send a pull request, right?

**Comment by TheBosZ** [comment]
Yes, they could submit a PR and I'd be happy to integrate it.

**Comment by jinuem** [comment]
Actually i managed to find out this error. Header allies inside Fabric framework is not working.

Inside Plugin/twitter-connect-plugin/src/ios/

Tried replacing the Fabric Framework and TwitterKit Framework from official Fabric Git. and Resolved this Issue. but Stuck with other issue.. Hope this Plugin will fix all issues soon :)

**Comment by gagandesires** [comment]
I had the same error. For me adding social.framework & coreData.framework in xcode libraries worked.

**Comment by jinuem** [comment]
@gagandesires  tried social.framework & coreData.framework..
still i get few errors.

**Comment by jinuem** [comment]
Fixed this iOS issue. Please anyone try it out and tell me is it working from your end.
Here is the Fixed Fork : https://github.com/jinuem/twitter-connect-plugin
(P.S: TwitterKit wont support below iOS7, so change the development to iOS7 or higher)
